# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor called X with a shape  of `(4, 2)`. Print X and it's shape.


In [1]:
# Import torch
import torch
# Create random tensor
X = torch.rand(size=(4, 2))
X, X.shape

(tensor([[0.8337, 0.3438],
         [0.4239, 0.8878],
         [0.2411, 0.4559],
         [0.3605, 0.5034]]),
 torch.Size([4, 2]))

### 3. Set Z equal to a matrix multiplication between tensor X and another random tensor called Y with a shape of  `(3, 2)` (hint: you may have to transpose Y).  Print Z and it's shape.

In [5]:
# Create another random tensor
Y = torch.rand(size=(3, 2))
# Perform matrix multiplication 
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[0.4245, 0.3069, 0.1423],
         [0.5309, 0.6293, 0.3445],
         [0.2803, 0.3254, 0.1772],
         [0.3403, 0.3682, 0.1969]]),
 torch.Size([4, 3]))

### 4. Set the RANDOM_SEED variable to `0`, then set the seed to RANDOM_SEED and do 2 & 3 over again. (make new variables)

The output should be:
```
tensor([[0.7119, 0.4817, 0.1408],
        [0.1238, 0.0839, 0.0243],
        [0.5410, 0.3620, 0.1139],
        [0.7901, 0.5311, 0.1623]])
```

In [13]:
# Set manual seed
RANDOM_SEED=0
torch.manual_seed(seed=RANDOM_SEED) 
# Create two random tensors
X2 = torch.rand(size=(4, 2))
Y2 = torch.rand(size=(3, 2))
# Matrix multiply tensors
Z2 = torch.matmul(X2, Y2.T)
Z2

tensor([[0.7119, 0.4817, 0.1408],
        [0.1238, 0.0839, 0.0243],
        [0.5410, 0.3620, 0.1139],
        [0.7901, 0.5311, 0.1623]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `22078`.

In [11]:
# Set random seed
torch.cuda.manual_seed(22078)