# 00.2 PyTorch Fundamentals Solution

### 1. Documentation reading 

  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# Import Torch
import torch

### 2. Set the GPU random seed to `4321`.

In [2]:
# Set random seed on the GPU
torch.cuda.manual_seed(4321)


### 3. Create two random tensors of shape `(1, 5)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(6789)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cpu

(tensor([[0.9453, 0.8658, 0.8732, 0.3954, 0.5728]]),
 tensor([[0.6512, 0.3760, 0.8524, 0.9262, 0.7002]]))
```

In [3]:
# Set random seed
torch.manual_seed(6789)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
X = torch.rand(size=(1,5)).to(device)
Y = torch.rand(size=(1,5)).to(device)
X, Y

Device: cpu


(tensor([[0.9453, 0.8658, 0.8732, 0.3954, 0.5728]]),
 tensor([[0.6512, 0.3760, 0.8524, 0.9262, 0.7002]]))


### 4. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[2.4528]]), torch.Size([1, 1]))
```

In [4]:
# Perform matmul on tensor_A and tensor_B
Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[2.4528]]), torch.Size([1, 1]))

### 5. Find the maximum and minimum values of the output of 7.

In [5]:
# Find max
max = torch.max(Z)
# Find min
min = torch.min(Z)
max, min

(tensor(2.4528), tensor(2.4528))

### 6. Find the maximum and minimum index values of the output of 7.

In [6]:
# Find arg max
arg_max = torch.argmax(Z)
# Find arg min
arg_min = torch.argmin(Z)
arg_max, arg_min

(tensor(0), tensor(0))


### 7. Make a random tensor with shape `(1, 1, 1, 10)` then create a new tensor equal to the first with all the `1` dimensions removed. Set the seed to `8` and print out both tensors and their shapes.
The output should look like:

```
tensor([[[[0.5979, 0.8453, 0.9464, 0.2965, 0.5138, 0.6443, 0.8991, 0.0141,
           0.5785, 0.1218]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5979, 0.8453, 0.9464, 0.2965, 0.5138, 0.6443, 0.8991, 0.0141, 0.5785,
        0.1218]) torch.Size([10])

```

In [7]:
# Set seed
torch.manual_seed(8)

# Create random tensor
A = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
B = A.squeeze()

# Print out tensors
print(A, A.shape)
print(B, B.shape)


tensor([[[[0.5979, 0.8453, 0.9464, 0.2965, 0.5138, 0.6443, 0.8991, 0.0141,
           0.5785, 0.1218]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5979, 0.8453, 0.9464, 0.2965, 0.5138, 0.6443, 0.8991, 0.0141, 0.5785,
        0.1218]) torch.Size([10])
